version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
      PAYJP_PRIVATE_KEY: ${PAYJP_PRIVATE_KEY}
      PAYJP_KEY: ${PAYJP_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/home_select_shop
    ports:
      - "3000:3000"
    links:
      - db
